title: ICLM
email: info@imperialcrownlogistics.com
description: >- # this means to ignore newlines until "baseurl:"
  Imperial Crown Logistics Mozambique
url: "https://imperialcrownlogistics.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
exclude:
  - Gemfile
  - Gemfile.lock
  - bower_components
  - node_modules
  - vendor

# Assets
sass:
  sass_dir: assets/_sass
  style: compressed


logo: /assets/img/logo.svg
image: /assets/img/logotipo.svg

color: "#0078C0"

collections_dir: collections
collections:
  about:
  services:
  clients:
  gallery:

# Pagination Settings
pagination:
  enabled: true
  per_page: 20
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2