title: ICLM
email: info@imperialcrownlogistics.com
description: >- # this means to ignore newlines until "baseurl:"
  Imperial Crown Logistics Mozambique
url: "https://imperialcrownlogistics.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-email-protect
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-analytics

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bower_components

# assets
sass:
  sass_dir: assets/_sass
  style: compressed

logo: /assets/img/logo.svg
image: /assets/img/logotipo.svg 
color: "#0078C0"

collections_dir: collections
collections:
  header:
  about:
  services:
  partners:
  clients:
  opinions:
  portfolio: