backend:
  name: git-gateway
  accept_roles:
    - admin
    - client
  branch: v2019

logo_url: 'https://izitech.co/assets/img/IZILogotipo.svg'

media_folder: "assets/img/uploads"

collections:
  - label: "Services"
    name: "services"
    folder: "collections/_services"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}

  - label: "About"
    name: "about"
    folder: "collections/_about"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}

  - label: "Clients"
    name: "clients"
    folder: "collections/_clients"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}

  - label: "Gallery"
    name: "gallery"
    folder: "collections/_gallery"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}

- label: "Team"
    name: "team"
    folder: "collections/_team"
    create: true
    fields:
       - {label: "Image", name: "image", widget: "image"}
       - {label: "Name", name: "name", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}