backend:
  name: git-gateway
  accept_roles:
    - admin
    - client
  branch: master

media_folder: "assets/img/uploads"
  
collections:
  - label: "About"
    name: "about"
    folder: "collections/_about"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - label: "Icon"
        name: "icon"
        widget: "select"
        options: ["eye", "tasks", "handshake"]
      - {label: "Description", name: "description", widget: "markdown"}

  - label: "Services"
    name: "services"
    folder: "collections/_services"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - label: "Icon"
        name: "icon"
        widget: "select"
        options: ["ship", "plane", "truck"]
      - {label: "Description", name: "description", widget: "markdown"}

  - label: "Partners"
    name: "partners"
    folder: "collections/_partners"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "markdown"}

  - label: "Clients"
    name: "clients"
    folder: "collections/_clients"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "markdown"}

  - label: "Slider"
    name: "slider"
    folder: "collections/_slider"
    create: true
    widget: "list"
    fields:
      - {label: Imagem, name: image, widget: "image"} 

  - label: "Locations"
    name: "locations"
    folder: "collections/_locations"
    create: true
    fields:
      - {label: "Province", name: "province", widget: "text"}
      - {label: "Location", name: "location", widget: "text"}