backend:
  name: git-gateway
  accept_roles:
    - admin
    - client
  branch: v2019

media_folder: "assets/img/uploads"

  - label: "Services"
    name: "services"
    folder: "collections/_services"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Icons", name: "icon", widget: "string"}
      - {label: "Corpo", name: "body", widget: "markdown"}

  - label: "About"
    name: "about"
    folder: "collections/_about"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Corpo", name: "body", widget: "markdown"}

  - label: "Clients"
    name: "clients"
    folder: "collections/_clients"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "markdown"}

  - label: "Partners"
    name: "partners"
    folder: "collections/_partners"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "markdown"}

  - label: "Locations"
    name: "locations"
    folder: "collections/_locations"
    create: true
    fields:
      - {label: "Province", name: "province", widget: "markdown"}
      - {label: "Location", name: "location", widget: "markdown"}

- label: "Tean"
    name: "team"
    folder: "collections/_team"
    create: true
    fields:
       - {label: "Image", name: "image", widget: "image"}
       - {label: "Name", name: "name", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}